apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: receiver
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: receiver-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 5
