apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
        - name: receiver
          image: mustafais/sender
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 500m
          env:
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@production-rabbitmqcluster.default.svc.cluster.local:5672"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: receiver-service
spec:
  selector:
    app: receiver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: LoadBalancer
