apiVersion: batch/v1
kind: Job
metadata:
  name: sender-job
spec:
  template:
    spec:
      containers:
      - name: sender
        image: mustafais/sender
        command: ["node",  "sender.js"]
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@production-rabbitmqcluster.default.svc.cluster.local:5672"
        - name: QUEUE
          value: "tasks"
        - name: INTERVAL
          value: "100"
      restartPolicy: Never
